# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3ef7e037c5f0fe8e1721502ca839b8c2f7df6069e433e407691bac2a5fe46fcc570273dd8e6cec8462711f1b65b0b1f945651d77f1bcf03e9df3e57b5953e21

test:
  secret_key_base: 48e1db50a6d295d4857810401b5bfa2031b87640b70fcee9cdade1674be048e9b4c4d0024771628cdb4fd60546ca3795f593699e0deddc8879a82edb53675181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
